-- AlterTable
ALTER TABLE `User` MODIFY `grad` ENUM('NEAPROBAT', 'VOLUNTAR', 'SPONSOR', 'MEMBRU', 'PARTENER', 'MENTOR', 'BOARD', 'TEAM_LEADER_TEHNIC', 'TEAM_LEADER_NON_TEHNIC', 'TEAM_LEADER', 'MINA') NOT NULL DEFAULT 'NEAPROBAT';
